Feat: Add onboarding finalization for users after successful payment
GDG-W/Asgard pull request #8
Opened 2024-07-22 01:48 UTC by RIDUMATICS

2024-07-22 07:50 UTC, Emmanuerl requested changes

2024-07-22 07:50 UTC, Emmanuerl commented on src/checkouts/checkout.model.ts
> +  attendees: { email_address: string; ticket_id: string }[] | User[];
no, they're different, revert this.

2024-07-22 07:50 UTC, Emmanuerl commented on src/users/user.model.ts
> -    super(`User "${email}" not found`);
this will break existing functionalities, you should work around it, not remove it

2024-07-22 07:50 UTC, Emmanuerl commented on src/users/user.repo.ts
> +      if (!filter || Object.keys(filter).length === 0) {
technically, it's not required, this extra check is unnecessary

2024-07-22 07:50 UTC, Emmanuerl commented on src/users/user.repo.ts
> +      return this.db(ctx).where(filter).first();
no, no, this is two database calls, we don't have to make 2 calls with postgres

```ts
const [user] = await this.db(ctx).where(filter).update(details,"*")
return user;
```

2024-07-22 07:50 UTC, Emmanuerl commented on src/users/user.service.ts
> +  async update(filter: Partial<User>, data: Partial<User>) {
since it's a service class it's params should be more direct for it's use case. using Partials is loose validation that should only happen at the repository layer cause we know the db can actually handle validations and many at times, we're already careful of the data getting there, however, a service is meant to prepare the data for the repo so it should be more validated but at compile and run time, that's why the `login` method has proper typings that aren't loose.

2024-07-23 17:06 UTC, RIDUMATICS commented on src/users/user.model.ts
> -    super(`User "${email}" not found`);
When I checked the code, I noticed that the method wasn't being used, so I removed it.

2024-07-27 16:44 UTC, Emmanuerl approved these changes

2024-07-27 16:44 UTC, merged